version: '3.3'

services:

  server:
    build:
      context: ./application/backend/
      dockerfile: Dockerfile
    ports:
      - 5002:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres

  postgres:
    build:
      context: ./application/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  multiplayer:
    build:
      context: ./application/multiplayer
      dockerfile: Dockerfile
    ports: 
      - 5003:5002