# base image
FROM python:latest

# install netcat
RUN apt-get update && \
    apt-get -y install netcat && \
    apt-get clean

# set working directory
WORKDIR /usr/src/app

# add and install requirements
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# add start-server.sh
COPY ./start-server.sh /usr/src/app/start-server.sh
RUN chmod +x /usr/src/app/start-server.sh

# add app
COPY . /usr/src/app

# run server
CMD ["/usr/src/app/start-server.sh"]