apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels: 
    name: flask
  name: flask
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  selector:
    matchLabels: flask
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flask
    spec:
      containers:
        - env:
          - name: FLASK_ENV
            value: development
            