 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: multiplayer-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: multiplayer-pv
  storageClassName: standard